/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferentesIndexRouteImport } from './routes/referentes.index'
import { Route as ReferentesIdRouteImport } from './routes/referentes.$id'
import { Route as UCodeRouteImport } from './routes/u.$code'
import { Route as ChatCodeRouteImport } from './routes/chat.$code'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentesIndexRoute = ReferentesIndexRouteImport.update({
  id: '/referentes/',
  path: '/referentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentesIdRoute = ReferentesIdRouteImport.update({
  id: '/referentes/$id',
  path: '/referentes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UCodeRoute = UCodeRouteImport.update({
  id: '/u/$code',
  path: '/u/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCodeRoute = ChatCodeRouteImport.update({
  id: '/chat/$code',
  path: '/chat/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/wallet': typeof WalletRoute
  '/referentes/$id': typeof ReferentesIdRoute
  '/referentes/': typeof ReferentesIndexRoute
  '/u/$code': typeof UCodeRoute
  '/chat/$code': typeof ChatCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/wallet': typeof WalletRoute
  '/referentes/$id': typeof ReferentesIdRoute
  '/referentes': typeof ReferentesIndexRoute
  '/u/$code': typeof UCodeRoute
  '/chat/$code': typeof ChatCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/wallet': typeof WalletRoute
  '/referentes/$id': typeof ReferentesIdRoute
  '/referentes/': typeof ReferentesIndexRoute
  '/u/$code': typeof UCodeRoute
  '/chat/$code': typeof ChatCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/noticias'
    | '/perfil'
    | '/wallet'
    | '/referentes/$id'
    | '/referentes/'
    | '/u/$code'
    | '/chat/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/noticias'
    | '/perfil'
    | '/wallet'
    | '/referentes/$id'
    | '/referentes'
    | '/u/$code'
    | '/chat/$code'
  id:
    | '__root__'
    | '/'
    | '/noticias'
    | '/perfil'
    | '/wallet'
    | '/referentes/$id'
    | '/referentes/'
    | '/u/$code'
    | '/chat/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticiasRoute: typeof NoticiasRoute
  PerfilRoute: typeof PerfilRoute
  WalletRoute: typeof WalletRoute
  ReferentesIdRoute: typeof ReferentesIdRoute
  ReferentesIndexRoute: typeof ReferentesIndexRoute
  UCodeRoute: typeof UCodeRoute
  ChatCodeRoute: typeof ChatCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referentes/': {
      id: '/referentes/'
      path: '/referentes'
      fullPath: '/referentes/'
      preLoaderRoute: typeof ReferentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referentes/$id': {
      id: '/referentes/$id'
      path: '/referentes/$id'
      fullPath: '/referentes/$id'
      preLoaderRoute: typeof ReferentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$code': {
      id: '/u/$code'
      path: '/u/$code'
      fullPath: '/u/$code'
      preLoaderRoute: typeof UCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$code': {
      id: '/chat/$code'
      path: '/chat/$code'
      fullPath: '/chat/$code'
      preLoaderRoute: typeof ChatCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticiasRoute: NoticiasRoute,
  PerfilRoute: PerfilRoute,
  WalletRoute: WalletRoute,
  ReferentesIdRoute: ReferentesIdRoute,
  ReferentesIndexRoute: ReferentesIndexRoute,
  UCodeRoute: UCodeRoute,
  ChatCodeRoute: ChatCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
