/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InformeRouteImport } from './routes/informe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferentesIndexRouteImport } from './routes/referentes.index'
import { Route as UCodeRouteImport } from './routes/u.$code'
import { Route as ReferentesIdRouteImport } from './routes/referentes.$id'
import { Route as ChatCodeRouteImport } from './routes/chat.$code'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicCronNotificationsRouteImport } from './routes/api/public/cron.notifications'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InformeRoute = InformeRouteImport.update({
  id: '/informe',
  path: '/informe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentesIndexRoute = ReferentesIndexRouteImport.update({
  id: '/referentes/',
  path: '/referentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const UCodeRoute = UCodeRouteImport.update({
  id: '/u/$code',
  path: '/u/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentesIdRoute = ReferentesIdRouteImport.update({
  id: '/referentes/$id',
  path: '/referentes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCodeRoute = ChatCodeRouteImport.update({
  id: '/chat/$code',
  path: '/chat/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotificationsRoute =
  ApiPublicCronNotificationsRouteImport.update({
    id: '/api/public/cron/notifications',
    path: '/api/public/cron/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informe': typeof InformeRoute
  '/legal': typeof LegalRoute
  '/noticias': typeof NoticiasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/chat/$code': typeof ChatCodeRoute
  '/referentes/$id': typeof ReferentesIdRoute
  '/u/$code': typeof UCodeRoute
  '/referentes/': typeof ReferentesIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informe': typeof InformeRoute
  '/legal': typeof LegalRoute
  '/noticias': typeof NoticiasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/chat/$code': typeof ChatCodeRoute
  '/referentes/$id': typeof ReferentesIdRoute
  '/u/$code': typeof UCodeRoute
  '/referentes': typeof ReferentesIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informe': typeof InformeRoute
  '/legal': typeof LegalRoute
  '/noticias': typeof NoticiasRoute
  '/notificaciones': typeof NotificacionesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/chat/$code': typeof ChatCodeRoute
  '/referentes/$id': typeof ReferentesIdRoute
  '/u/$code': typeof UCodeRoute
  '/referentes/': typeof ReferentesIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/informe'
    | '/legal'
    | '/noticias'
    | '/notificaciones'
    | '/onboarding'
    | '/perfil'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/chat/$code'
    | '/referentes/$id'
    | '/u/$code'
    | '/referentes/'
    | '/api/public/stripe-webhook'
    | '/api/public/cron/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/informe'
    | '/legal'
    | '/noticias'
    | '/notificaciones'
    | '/onboarding'
    | '/perfil'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/chat/$code'
    | '/referentes/$id'
    | '/u/$code'
    | '/referentes'
    | '/api/public/stripe-webhook'
    | '/api/public/cron/notifications'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/informe'
    | '/legal'
    | '/noticias'
    | '/notificaciones'
    | '/onboarding'
    | '/perfil'
    | '/privacy'
    | '/terms'
    | '/wallet'
    | '/chat/$code'
    | '/referentes/$id'
    | '/u/$code'
    | '/referentes/'
    | '/api/public/stripe-webhook'
    | '/api/public/cron/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InformeRoute: typeof InformeRoute
  LegalRoute: typeof LegalRoute
  NoticiasRoute: typeof NoticiasRoute
  NotificacionesRoute: typeof NotificacionesRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  ChatCodeRoute: typeof ChatCodeRoute
  ReferentesIdRoute: typeof ReferentesIdRoute
  UCodeRoute: typeof UCodeRoute
  ReferentesIndexRoute: typeof ReferentesIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicCronNotificationsRoute: typeof ApiPublicCronNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informe': {
      id: '/informe'
      path: '/informe'
      fullPath: '/informe'
      preLoaderRoute: typeof InformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referentes/': {
      id: '/referentes/'
      path: '/referentes'
      fullPath: '/referentes/'
      preLoaderRoute: typeof ReferentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$code': {
      id: '/u/$code'
      path: '/u/$code'
      fullPath: '/u/$code'
      preLoaderRoute: typeof UCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referentes/$id': {
      id: '/referentes/$id'
      path: '/referentes/$id'
      fullPath: '/referentes/$id'
      preLoaderRoute: typeof ReferentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$code': {
      id: '/chat/$code'
      path: '/chat/$code'
      fullPath: '/chat/$code'
      preLoaderRoute: typeof ChatCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notifications': {
      id: '/api/public/cron/notifications'
      path: '/api/public/cron/notifications'
      fullPath: '/api/public/cron/notifications'
      preLoaderRoute: typeof ApiPublicCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InformeRoute: InformeRoute,
  LegalRoute: LegalRoute,
  NoticiasRoute: NoticiasRoute,
  NotificacionesRoute: NotificacionesRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  ChatCodeRoute: ChatCodeRoute,
  ReferentesIdRoute: ReferentesIdRoute,
  UCodeRoute: UCodeRoute,
  ReferentesIndexRoute: ReferentesIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicCronNotificationsRoute: ApiPublicCronNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
